pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20240910085823/test_queue_no_inplace/main
  - label=queue
  name: default merge
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
