pull_request_rules:
- actions:
    close: {}
  conditions:
  - base=20240801143117/test_disabled/main
  - -closed
  - label!=foo
  disabled:
    reason: code freeze
  name: merge
- actions: {}
  conditions:
  - base=20240801143117/test_disabled/main
  - closed
  - label=foo
  name: nothing
