pull_request_rules:
- actions:
    request_reviews:
      teams:
      - '@atchoum'
      - atchoum
  conditions:
  - base=20240801150247/test_pull_request_with_invalid_team_name_in_new_configuration/main
  name: foobar
