pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20240906113002/test_queue_inplace_train_resetted/main
  - check-success=continuous-integration/fake-ci
  - -conflict
  name: Merge priority high
queue_rules:
- conditions:
  - check-success=continuous-integration/fake-ci
  name: default
