pull_request_rules:
- actions:
    post_check: {}
  conditions:
  - base=20260303112612/test_post_check_basic/main
  - body~=(?m)^(Fixes|Related|Closes) (MERGIFY-ENGINE|MRGFY)-
  name: body need sentry ticket
