pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20240503091032/test_bypass_branch_protections_with_queue_injection_mode/main
  - label=queue
  name: Merge default
queue_rules:
- branch_protection_injection_mode: queue
  merge_conditions: []
  name: default
