pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20240910151044/test_rebase_pr_in_queue/main
  - label=queue
  name: Automatic merge
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
