pull_request_rules:
- actions:
    merge:
      method: squash
  conditions:
  - base=20240507091402/test_merge_custom_msg_case/main
  - status-success=continuous-integration/fake-ci
  name: Merge on main
