pull_request_rules:
- actions:
    github_actions:
      workflow:
        dispatch:
        - ref: 20240514141444/test_gha_unknown_workflow/main
          workflow: unknown.yaml
  conditions:
  - label=dispatch
  name: Dispatch unknown workflow
