pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20240507091514/test_merge_custom_msg_template/main
  - status-success=continuous-integration/fake-ci
  name: Merge on main
